# Generated by Django 4.0.5 on 2022-06-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_alter_employeeuser_designations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeuser',
            name='designations',
            field=models.CharField(choices=[('ASSOCIATE SOFTWARE ENGINEER', 'Associate Software Engineer'), ('SOFTWARE ENGINEER', 'Software Engineer'), ('TRAINEE ENGINEER', 'Trainee Engineer')], max_length=40),
        ),
    ]
