# Generated by Django 4.0.5 on 2022-06-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_alter_employeeuser_designations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeuser',
            name='designations',
            field=models.CharField(choices=[('TRAINEE ENGINEER', 'Trainee Engineer'), ('SOFTWARE ENGINEER', 'Software Engineer'), ('ASSOCIATE SOFTWARE ENGINEER', 'Associate Software Engineer')], max_length=40),
        ),
        migrations.AlterField(
            model_name='employeeuser',
            name='phone_no',
            field=models.IntegerField(max_length=20),
        ),
    ]
